name: Test

on:
    push:
        branches:
            - main
    pull_request:

jobs:

    Tests:
        name: 'T3 ${{ matrix.typo3 }} - PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}'
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                typo3: [ '^11.5.36', '^12.4.14' ]
                php: [ '8.1', '8.2' ]
                dependency-version: [ stable, lowest  ]
                experimental: [ false ]

        continue-on-error: ${{ matrix.experimental }}

        steps:
            -   name: Start database server
                run: sudo /etc/init.d/mysql start

            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Composer Cache Vars
                id: composer-cache-vars
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
                    echo "timestamp=$(date +"%s")" >> $GITHUB_OUTPUT

            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache-vars.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ matrix.typo3 }}-${{ matrix.dependency-version }}-${{ matrix.php }}-${{ steps.composer-cache-vars.outputs.timestamp }}
                    restore-keys: |
                        ${{ runner.os }}-composer-${{ matrix.typo3 }}-${{ matrix.dependency-version }}-${{ matrix.php }}-
                        ${{ runner.os }}-composer-${{ matrix.typo3 }}-${{ matrix.dependency-version }}-
                        ${{ runner.os }}-composer-${{ matrix.typo3 }}-
                        ${{ runner.os }}-composer-

            -   name: Set up PHP Version ${{ matrix.php }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    tools: cs2pr

            -   name: Environment Check
                run: |
                    php --version
                    composer --version

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install
                run: |
                    composer update --with typo3/cms-core="${{ matrix.typo3 }}" --prefer-${{ matrix.dependency-version }} --prefer-dist --no-interaction

            -   name: Lint
                run: vendor/bin/parallel-lint . --exclude vendor --exclude var --exclude public --checkstyle | cs2pr --notices-as-warnings --colorize

            -   name: CS fixer
                run: vendor/bin/php-cs-fixer fix -n --diff --format=checkstyle --dry-run | cs2pr --notices-as-warnings --colorize

            -   name: Phpstan
                run: vendor/bin/phpstan analyse -c "phpstan${{ matrix.typo3 }}.neon" --error-format=checkstyle | cs2pr --notices-as-warnings --colorize

            -   name: Configure matchers
                uses: mheap/phpunit-matcher-action@v1

            -   name: Unit Tests
                run: vendor/bin/phpunit --teamcity
